"""initial schema

Revision ID: 7000dcb96cc5
Revises: 
Create Date: 2026-09-21 22:42:05.823955
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '7000dcb96cc5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('task', sa.String(length=64), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cached_input_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=False),
    sa.Column('cache_status', sa.String(length=32), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('briefing_id', sa.Integer(), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('outlook_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_usage_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_usage_model'), ['model'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_usage_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_usage_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_usage_task'), ['task'], unique=False)
        batch_op.create_index('ix_ai_usage_task_time', ['task', 'occurred_at'], unique=False)

    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_settings_created_at'), ['created_at'], unique=False)

    op.create_table('lunar_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('exact_at', sa.DateTime(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('strength_score', sa.Float(), nullable=True),
    sa.Column('strength_components_json', sa.Text(), nullable=False),
    sa.Column('nodal_distance_deg', sa.Float(), nullable=True),
    sa.Column('ecliptic_longitude_deg', sa.Float(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('is_eclipse', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lunar_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lunar_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_lunar_events_event_date'), ['event_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_lunar_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_lunar_events_exact_at'), ['exact_at'], unique=False)
        batch_op.create_index('ix_lunar_type_date', ['event_type', 'event_date'], unique=False)

    op.create_table('market_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('open_price', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('change_24h_pct', sa.Float(), nullable=True),
    sa.Column('change_7d_pct', sa.Float(), nullable=True),
    sa.Column('volatility_30d', sa.Float(), nullable=True),
    sa.Column('ma50', sa.Float(), nullable=True),
    sa.Column('ma200', sa.Float(), nullable=True),
    sa.Column('rsi14', sa.Float(), nullable=True),
    sa.Column('support_levels_json', sa.Text(), nullable=False),
    sa.Column('resistance_levels_json', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('raw_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('market_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_snapshots_captured_at'), ['captured_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_snapshots_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_snapshots_snapshot_date'), ['snapshot_date'], unique=False)

    op.create_table('natal_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transiting_body', sa.String(length=48), nullable=False),
    sa.Column('natal_point', sa.String(length=48), nullable=False),
    sa.Column('aspect', sa.String(length=32), nullable=False),
    sa.Column('exact_at', sa.DateTime(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('orb_deg', sa.Float(), nullable=True),
    sa.Column('is_applying', sa.Boolean(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('interpretation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('natal_events', schema=None) as batch_op:
        batch_op.create_index('ix_natal_date_body', ['event_date', 'transiting_body'], unique=False)
        batch_op.create_index(batch_op.f('ix_natal_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_natal_events_event_date'), ['event_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_natal_events_exact_at'), ['exact_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_natal_events_transiting_body'), ['transiting_body'], unique=False)

    op.create_table('outlooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=191), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('body_markdown', sa.Text(), nullable=False),
    sa.Column('natal_context_json', sa.Text(), nullable=False),
    sa.Column('lunar_context_json', sa.Text(), nullable=False),
    sa.Column('technical_context_json', sa.Text(), nullable=False),
    sa.Column('events_json', sa.Text(), nullable=False),
    sa.Column('levels_json', sa.Text(), nullable=False),
    sa.Column('review_markdown', sa.Text(), nullable=False),
    sa.Column('review_recorded_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('visibility', sa.String(length=16), nullable=False),
    sa.Column('provenance', sa.String(length=48), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('required_entitlement', sa.String(length=64), nullable=False),
    sa.Column('meta_description', sa.String(length=320), nullable=False),
    sa.Column('ai_generated', sa.Boolean(), nullable=False),
    sa.Column('ai_model', sa.String(length=120), nullable=False),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('outlooks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outlooks_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_outlooks_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_outlooks_period_start'), ['period_start'], unique=False)
        batch_op.create_index(batch_op.f('ix_outlooks_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_outlooks_status'), ['status'], unique=False)

    op.create_table('research_briefings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('briefing_date', sa.Date(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('headline', sa.String(length=255), nullable=False),
    sa.Column('body_markdown', sa.Text(), nullable=False),
    sa.Column('context_json', sa.Text(), nullable=False),
    sa.Column('triage', sa.String(length=48), nullable=False),
    sa.Column('triage_note', sa.Text(), nullable=False),
    sa.Column('ai_generated', sa.Boolean(), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=False),
    sa.Column('visibility', sa.String(length=16), nullable=False),
    sa.Column('job_run_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('research_briefings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_briefings_briefing_date'), ['briefing_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_briefings_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_briefings_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_briefings_triage'), ['triage'], unique=False)

    op.create_table('research_protocols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=191), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('rules_json', sa.Text(), nullable=False),
    sa.Column('window_start', sa.DateTime(), nullable=True),
    sa.Column('window_end', sa.DateTime(), nullable=True),
    sa.Column('is_frozen', sa.Boolean(), nullable=False),
    sa.Column('frozen_at', sa.DateTime(), nullable=True),
    sa.Column('supersedes_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('provenance', sa.String(length=48), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['supersedes_id'], ['research_protocols.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('research_protocols', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_protocols_created_at'), ['created_at'], unique=False)

    op.create_table('scheduled_job_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_name', sa.String(length=120), nullable=False),
    sa.Column('idempotency_key', sa.String(length=191), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    with op.batch_alter_table('scheduled_job_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scheduled_job_runs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_job_runs_job_name'), ['job_name'], unique=False)

    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=191), nullable=False),
    sa.Column('name', sa.String(length=191), nullable=False),
    sa.Column('homepage', sa.String(length=500), nullable=False),
    sa.Column('feed_url', sa.String(length=500), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('default_category', sa.String(length=48), nullable=False),
    sa.Column('is_authoritative', sa.Boolean(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sources_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sources_is_enabled'), ['is_enabled'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=191), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('visibility', sa.String(length=16), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_last_message_at'), ['last_message_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_user_id'), ['user_id'], unique=False)

    op.create_table('experiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=191), nullable=False),
    sa.Column('ref', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('protocol_id', sa.Integer(), nullable=True),
    sa.Column('observed_at', sa.DateTime(), nullable=True),
    sa.Column('starts_at', sa.DateTime(), nullable=True),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.Column('moon_context_json', sa.Text(), nullable=False),
    sa.Column('btc_snapshot_json', sa.Text(), nullable=False),
    sa.Column('natal_context_json', sa.Text(), nullable=False),
    sa.Column('technical_context', sa.Text(), nullable=False),
    sa.Column('market_news_context', sa.Text(), nullable=False),
    sa.Column('hypothesis_text', sa.Text(), nullable=False),
    sa.Column('prediction_text', sa.Text(), nullable=False),
    sa.Column('confidence', sa.String(length=64), nullable=False),
    sa.Column('test_criteria', sa.Text(), nullable=False),
    sa.Column('invalidation_criteria', sa.Text(), nullable=False),
    sa.Column('experiment_status', sa.String(length=32), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('result_text', sa.Text(), nullable=False),
    sa.Column('timing_error_days', sa.Float(), nullable=True),
    sa.Column('subsequent_high', sa.Float(), nullable=True),
    sa.Column('subsequent_low', sa.Float(), nullable=True),
    sa.Column('lessons', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('visibility', sa.String(length=16), nullable=False),
    sa.Column('provenance', sa.String(length=48), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('result_recorded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['protocol_id'], ['research_protocols.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experiments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_experiments_experiment_status'), ['experiment_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_experiments_observed_at'), ['observed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_experiments_outcome'), ['outcome'], unique=False)
        batch_op.create_index(batch_op.f('ix_experiments_provenance'), ['provenance'], unique=False)
        batch_op.create_index(batch_op.f('ix_experiments_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_experiments_status'), ['status'], unique=False)

    op.create_table('news_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('headline', sa.String(length=500), nullable=False),
    sa.Column('canonical_url', sa.String(length=700), nullable=False),
    sa.Column('publisher', sa.String(length=191), nullable=False),
    sa.Column('source_published_at', sa.DateTime(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(), nullable=False),
    sa.Column('category', sa.String(length=48), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('editor_note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fingerprint')
    )
    with op.batch_alter_table('news_items', schema=None) as batch_op:
        batch_op.create_index('ix_news_cat_relevance', ['category', 'relevance_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_items_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_items_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_items_is_featured'), ['is_featured'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_items_relevance_score'), ['relevance_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_items_retrieved_at'), ['retrieved_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_items_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_items_source_published_at'), ['source_published_at'], unique=False)

    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('entitlements', sa.Text(), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=True),
    sa.Column('external_ref', sa.String(length=191), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_user_id'), ['user_id'], unique=False)

    op.create_table('hypotheses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=191), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('test_criteria', sa.Text(), nullable=False),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('visibility', sa.String(length=16), nullable=False),
    sa.Column('provenance', sa.String(length=48), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('hypotheses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hypotheses_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_hypotheses_experiment_id'), ['experiment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hypotheses_status'), ['status'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('context_json', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('ai_usage_id', sa.Integer(), nullable=True),
    sa.Column('visibility', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_created_at'), ['created_at'], unique=False)

    op.create_table('observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=191), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=True),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('btc_snapshot_json', sa.Text(), nullable=False),
    sa.Column('moon_context_json', sa.Text(), nullable=False),
    sa.Column('sources_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('visibility', sa.String(length=16), nullable=False),
    sa.Column('provenance', sa.String(length=48), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_observations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_observations_experiment_id'), ['experiment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_observations_observed_at'), ['observed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_observations_provenance'), ['provenance'], unique=False)
        batch_op.create_index(batch_op.f('ix_observations_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_observations_status'), ['status'], unique=False)

    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=191), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=True),
    sa.Column('protocol_id', sa.Integer(), nullable=True),
    sa.Column('prediction_text', sa.Text(), nullable=False),
    sa.Column('test_criteria', sa.Text(), nullable=False),
    sa.Column('invalidation_criteria', sa.Text(), nullable=False),
    sa.Column('confidence', sa.String(length=64), nullable=False),
    sa.Column('evidence_snapshot_json', sa.Text(), nullable=False),
    sa.Column('made_at', sa.DateTime(), nullable=False),
    sa.Column('horizon_end', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('visibility', sa.String(length=16), nullable=False),
    sa.Column('provenance', sa.String(length=48), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.ForeignKeyConstraint(['protocol_id'], ['research_protocols.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_predictions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_predictions_experiment_id'), ['experiment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_predictions_horizon_end'), ['horizon_end'], unique=False)
        batch_op.create_index(batch_op.f('ix_predictions_made_at'), ['made_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_predictions_outcome'), ['outcome'], unique=False)
        batch_op.create_index(batch_op.f('ix_predictions_provenance'), ['provenance'], unique=False)
        batch_op.create_index(batch_op.f('ix_predictions_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_predictions_status'), ['status'], unique=False)

    op.create_table('technical_patterns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=191), nullable=False),
    sa.Column('name', sa.String(length=191), nullable=False),
    sa.Column('pattern_type', sa.String(length=64), nullable=False),
    sa.Column('timeframe', sa.String(length=32), nullable=False),
    sa.Column('identified_at', sa.DateTime(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('trigger_level', sa.Float(), nullable=True),
    sa.Column('confirmation_low', sa.Float(), nullable=True),
    sa.Column('confirmation_high', sa.Float(), nullable=True),
    sa.Column('target_low', sa.Float(), nullable=True),
    sa.Column('target_high', sa.Float(), nullable=True),
    sa.Column('invalidation_level', sa.Float(), nullable=True),
    sa.Column('pattern_status', sa.String(length=32), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('resolution_note', sa.Text(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('visibility', sa.String(length=16), nullable=False),
    sa.Column('provenance', sa.String(length=48), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('technical_patterns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_technical_patterns_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_technical_patterns_identified_at'), ['identified_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_technical_patterns_status'), ['status'], unique=False)

    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=191), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=True),
    sa.Column('experiment_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('timing_error_days', sa.Float(), nullable=True),
    sa.Column('price_at_prediction', sa.Float(), nullable=True),
    sa.Column('price_at_result', sa.Float(), nullable=True),
    sa.Column('subsequent_high', sa.Float(), nullable=True),
    sa.Column('subsequent_low', sa.Float(), nullable=True),
    sa.Column('max_upside_pct', sa.Float(), nullable=True),
    sa.Column('max_downside_pct', sa.Float(), nullable=True),
    sa.Column('metrics_json', sa.Text(), nullable=False),
    sa.Column('lessons', sa.Text(), nullable=False),
    sa.Column('sources_json', sa.Text(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('result_recorded_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('visibility', sa.String(length=16), nullable=False),
    sa.Column('provenance', sa.String(length=48), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_results_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_results_experiment_id'), ['experiment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_results_outcome'), ['outcome'], unique=False)
        batch_op.create_index(batch_op.f('ix_results_prediction_id'), ['prediction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_results_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_results_recorded_at'), ['recorded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_results_status'), ['status'], unique=False)

    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=191), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('subtitle', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('body_markdown', sa.Text(), nullable=False),
    sa.Column('article_type', sa.String(length=48), nullable=False),
    sa.Column('record_kind', sa.String(length=32), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=True),
    sa.Column('prediction_id', sa.Integer(), nullable=True),
    sa.Column('observation_id', sa.Integer(), nullable=True),
    sa.Column('result_id', sa.Integer(), nullable=True),
    sa.Column('observed_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.Column('result_recorded_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('visibility', sa.String(length=16), nullable=False),
    sa.Column('provenance', sa.String(length=48), nullable=False),
    sa.Column('sources_json', sa.Text(), nullable=False),
    sa.Column('meta_description', sa.String(length=320), nullable=False),
    sa.Column('canonical_url', sa.String(length=500), nullable=False),
    sa.Column('og_image', sa.String(length=500), nullable=False),
    sa.Column('noindex', sa.Boolean(), nullable=False),
    sa.Column('required_entitlement', sa.String(length=64), nullable=False),
    sa.Column('ai_generated', sa.Boolean(), nullable=False),
    sa.Column('ai_model', sa.String(length=120), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.id'], ),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.ForeignKeyConstraint(['result_id'], ['results.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_articles_article_type'), ['article_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_experiment_id'), ['experiment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_observed_at'), ['observed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_provenance'), ['provenance'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_articles_status'))
        batch_op.drop_index(batch_op.f('ix_articles_published_at'))
        batch_op.drop_index(batch_op.f('ix_articles_provenance'))
        batch_op.drop_index(batch_op.f('ix_articles_observed_at'))
        batch_op.drop_index(batch_op.f('ix_articles_experiment_id'))
        batch_op.drop_index(batch_op.f('ix_articles_created_at'))
        batch_op.drop_index(batch_op.f('ix_articles_article_type'))

    op.drop_table('articles')
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_results_status'))
        batch_op.drop_index(batch_op.f('ix_results_recorded_at'))
        batch_op.drop_index(batch_op.f('ix_results_published_at'))
        batch_op.drop_index(batch_op.f('ix_results_prediction_id'))
        batch_op.drop_index(batch_op.f('ix_results_outcome'))
        batch_op.drop_index(batch_op.f('ix_results_experiment_id'))
        batch_op.drop_index(batch_op.f('ix_results_created_at'))

    op.drop_table('results')
    with op.batch_alter_table('technical_patterns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_technical_patterns_status'))
        batch_op.drop_index(batch_op.f('ix_technical_patterns_identified_at'))
        batch_op.drop_index(batch_op.f('ix_technical_patterns_created_at'))

    op.drop_table('technical_patterns')
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_predictions_status'))
        batch_op.drop_index(batch_op.f('ix_predictions_published_at'))
        batch_op.drop_index(batch_op.f('ix_predictions_provenance'))
        batch_op.drop_index(batch_op.f('ix_predictions_outcome'))
        batch_op.drop_index(batch_op.f('ix_predictions_made_at'))
        batch_op.drop_index(batch_op.f('ix_predictions_horizon_end'))
        batch_op.drop_index(batch_op.f('ix_predictions_experiment_id'))
        batch_op.drop_index(batch_op.f('ix_predictions_created_at'))

    op.drop_table('predictions')
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_observations_status'))
        batch_op.drop_index(batch_op.f('ix_observations_published_at'))
        batch_op.drop_index(batch_op.f('ix_observations_provenance'))
        batch_op.drop_index(batch_op.f('ix_observations_observed_at'))
        batch_op.drop_index(batch_op.f('ix_observations_experiment_id'))
        batch_op.drop_index(batch_op.f('ix_observations_created_at'))

    op.drop_table('observations')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_created_at'))
        batch_op.drop_index(batch_op.f('ix_messages_conversation_id'))

    op.drop_table('messages')
    with op.batch_alter_table('hypotheses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hypotheses_status'))
        batch_op.drop_index(batch_op.f('ix_hypotheses_experiment_id'))
        batch_op.drop_index(batch_op.f('ix_hypotheses_created_at'))

    op.drop_table('hypotheses')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_user_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_created_at'))

    op.drop_table('subscriptions')
    with op.batch_alter_table('news_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_items_source_published_at'))
        batch_op.drop_index(batch_op.f('ix_news_items_source_id'))
        batch_op.drop_index(batch_op.f('ix_news_items_retrieved_at'))
        batch_op.drop_index(batch_op.f('ix_news_items_relevance_score'))
        batch_op.drop_index(batch_op.f('ix_news_items_is_featured'))
        batch_op.drop_index(batch_op.f('ix_news_items_created_at'))
        batch_op.drop_index(batch_op.f('ix_news_items_category'))
        batch_op.drop_index('ix_news_cat_relevance')

    op.drop_table('news_items')
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experiments_status'))
        batch_op.drop_index(batch_op.f('ix_experiments_published_at'))
        batch_op.drop_index(batch_op.f('ix_experiments_provenance'))
        batch_op.drop_index(batch_op.f('ix_experiments_outcome'))
        batch_op.drop_index(batch_op.f('ix_experiments_observed_at'))
        batch_op.drop_index(batch_op.f('ix_experiments_experiment_status'))
        batch_op.drop_index(batch_op.f('ix_experiments_created_at'))

    op.drop_table('experiments')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_user_id'))
        batch_op.drop_index(batch_op.f('ix_conversations_last_message_at'))
        batch_op.drop_index(batch_op.f('ix_conversations_created_at'))

    op.drop_table('conversations')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))

    op.drop_table('users')
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sources_is_enabled'))
        batch_op.drop_index(batch_op.f('ix_sources_created_at'))

    op.drop_table('sources')
    with op.batch_alter_table('scheduled_job_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheduled_job_runs_job_name'))
        batch_op.drop_index(batch_op.f('ix_scheduled_job_runs_created_at'))

    op.drop_table('scheduled_job_runs')
    with op.batch_alter_table('research_protocols', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_protocols_created_at'))

    op.drop_table('research_protocols')
    with op.batch_alter_table('research_briefings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_briefings_triage'))
        batch_op.drop_index(batch_op.f('ix_research_briefings_kind'))
        batch_op.drop_index(batch_op.f('ix_research_briefings_created_at'))
        batch_op.drop_index(batch_op.f('ix_research_briefings_briefing_date'))

    op.drop_table('research_briefings')
    with op.batch_alter_table('outlooks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outlooks_status'))
        batch_op.drop_index(batch_op.f('ix_outlooks_published_at'))
        batch_op.drop_index(batch_op.f('ix_outlooks_period_start'))
        batch_op.drop_index(batch_op.f('ix_outlooks_kind'))
        batch_op.drop_index(batch_op.f('ix_outlooks_created_at'))

    op.drop_table('outlooks')
    with op.batch_alter_table('natal_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_natal_events_transiting_body'))
        batch_op.drop_index(batch_op.f('ix_natal_events_exact_at'))
        batch_op.drop_index(batch_op.f('ix_natal_events_event_date'))
        batch_op.drop_index(batch_op.f('ix_natal_events_created_at'))
        batch_op.drop_index('ix_natal_date_body')

    op.drop_table('natal_events')
    with op.batch_alter_table('market_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_snapshots_snapshot_date'))
        batch_op.drop_index(batch_op.f('ix_market_snapshots_created_at'))
        batch_op.drop_index(batch_op.f('ix_market_snapshots_captured_at'))

    op.drop_table('market_snapshots')
    with op.batch_alter_table('lunar_events', schema=None) as batch_op:
        batch_op.drop_index('ix_lunar_type_date')
        batch_op.drop_index(batch_op.f('ix_lunar_events_exact_at'))
        batch_op.drop_index(batch_op.f('ix_lunar_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_lunar_events_event_date'))
        batch_op.drop_index(batch_op.f('ix_lunar_events_created_at'))

    op.drop_table('lunar_events')
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_settings_created_at'))

    op.drop_table('app_settings')
    with op.batch_alter_table('ai_usage', schema=None) as batch_op:
        batch_op.drop_index('ix_ai_usage_task_time')
        batch_op.drop_index(batch_op.f('ix_ai_usage_task'))
        batch_op.drop_index(batch_op.f('ix_ai_usage_provider'))
        batch_op.drop_index(batch_op.f('ix_ai_usage_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_ai_usage_model'))
        batch_op.drop_index(batch_op.f('ix_ai_usage_created_at'))

    op.drop_table('ai_usage')
    # ### end Alembic commands ###
